name: Minimal OIDC Test
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  oidc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Verify credentials
        run: aws sts get-caller-identity
